# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='upload/org/%Y%m', verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
    ]
